{
 "title": "HPC Cluster rosalind",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU core usage - whole cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total CPU cores",
     "measurement": "partition_cpu_total",
     "select": [
      [
       { "params": [ "cpu_total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=", "value": "ALL" }
     ]
    },
    {
     "alias": "Used CPU cores",
     "measurement": "partition_cpu_usage",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=", "value": "ALL" }
     ]
    }
   ]
  },
  {
   "title": "CPU core usage - partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "partition" ], "type": "tag" }
     ],
     "measurement": "partition_cpu_usage_pc",
     "select": [
      [
       { "params": [ "cpu_usage_pc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "!=", "value": "ALL" },
      { "condition": "AND", "key": "partition", "operator": "!=", "value": "test" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage - partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "partition" ], "type": "tag" }
     ],
     "measurement": "partition_mem_usage_pc",
     "select": [
      [
       { "params": [ "mem_usage_pc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "!=", "value": "ALL" },
      { "condition": "AND", "key": "partition", "operator": "!=", "value": "test" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage - whole cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Total memory",
     "measurement": "partition_mem_total",
     "select": [
      [
       { "params": [ "mem_total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=", "value": "ALL" }
     ]
    },
    {
     "alias": "Used memory",
     "measurement": "partition_mem_usage",
     "select": [
      [
       { "params": [ "mem_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=", "value": "ALL" }
     ]
    }
   ]
  },
  {
   "title": "GPU usage - partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "partition" ], "type": "tag" }
     ],
     "measurement": "partition_gpu_usage_pc",
     "select": [
      [
       { "params": [ "gpu_usage_pc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "!=", "value": "ALL" },
      { "condition": "AND", "key": "partition", "operator": "!=", "value": "test" }
     ]
    }
   ]
  },
  {
   "title": "GPU usage - whole cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total GPUs",
     "measurement": "partition_gpu_total",
     "select": [
      [
       { "params": [ "gpu_total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=", "value": "ALL" }
     ]
    },
    {
     "alias": "Used GPUs",
     "measurement": "partition_gpu_usage",
     "select": [
      [
       { "params": [ "gpu_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=", "value": "ALL" }
     ]
    }
   ]
  },
  {
   "title": "Jobs running - partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "partition" ], "type": "tag" }
     ],
     "measurement": "partition_jobs_running",
     "select": [
      [
       { "params": [ "jobs_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "!=", "value": "ALL" },
      { "condition": "AND", "key": "partition", "operator": "!=", "value": "test" }
     ]
    }
   ]
  },
  {
   "title": "Jobs - whole cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Jobs running",
     "measurement": "partition_jobs_running",
     "select": [
      [
       { "params": [ "jobs_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=", "value": "ALL" }
     ]
    },
    {
     "alias": "Jobs pending",
     "measurement": "partition_jobs_pending",
     "select": [
      [
       { "params": [ "jobs_pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=", "value": "ALL" }
     ]
    },
    {
     "alias": "Queue time",
     "measurement": "partition_queue_time",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "queue_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=", "value": "ALL" }
     ]
    }
   ]
  },
  {
   "title": "Queue time - partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "partition" ], "type": "tag" }
     ],
     "measurement": "partition_queue_time",
     "select": [
      [
       { "params": [ "queue_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "!=", "value": "ALL" },
      { "condition": "AND", "key": "partition", "operator": "!=", "value": "test" }
     ]
    }
   ]
  },
  {
   "title": "Jobs - users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_user - running",
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "user_jobs_running",
     "select": [
      [
       { "params": [ "jobs_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobs_running", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$tag_user - pending",
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "user_jobs_pending",
     "select": [
      [
       { "params": [ "jobs_pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobs_pending", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage - users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_user",
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "user_mem_usage",
     "select": [
      [
       { "params": [ "mem_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "mem_usage", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "CPU core usage - users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_user",
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "user_cpu_usage",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpu_usage", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "CPU core usage - groups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "group_cpu_usage",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU usage - users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_user",
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "user_gpu_usage",
     "select": [
      [
       { "params": [ "gpu_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "gpu_usage", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage - groups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "group_mem_usage",
     "select": [
      [
       { "params": [ "mem_usage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU core usage - departments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ldap_attrib",
     "groupBy": [
      { "params": [ "ldap_attrib" ], "type": "tag" }
     ],
     "measurement": "ldap_attrib_cpu_usage",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpu_usage", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "GPU usage - groups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "group_gpu_usage",
     "select": [
      [
       { "params": [ "gpu_usage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage - departments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ldap_attrib",
     "groupBy": [
      { "params": [ "ldap_attrib" ], "type": "tag" }
     ],
     "measurement": "ldap_attrib_mem_usage",
     "select": [
      [
       { "params": [ "mem_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "mem_usage", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Jobs running - groups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_group - running",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "group_jobs_running",
     "query": "SELECT \"jobs_running\" FROM \"group_jobs_running\" WHERE $timeFilter GROUP BY \"group\"",
     "select": [
      [
       { "params": [ "jobs_running" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU usage - departments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ldap_attrib",
     "groupBy": [
      { "params": [ "ldap_attrib" ], "type": "tag" }
     ],
     "measurement": "ldap_attrib_gpu_usage",
     "select": [
      [
       { "params": [ "gpu_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "gpu_usage", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Jobs pending - groups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "group_jobs_pending",
     "select": [
      [
       { "params": [ "jobs_pending" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs running - departments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ldap_attrib",
     "groupBy": [
      { "params": [ "ldap_attrib" ], "type": "tag" }
     ],
     "measurement": "ldap_attrib_jobs_running",
     "select": [
      [
       { "params": [ "jobs_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobs_running", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Queue time - groups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "group_queue_time",
     "select": [
      [
       { "params": [ "queue_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs pending - departments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ldap_attrib",
     "groupBy": [
      { "params": [ "ldap_attrib" ], "type": "tag" }
     ],
     "measurement": "ldap_attrib_jobs_pending",
     "select": [
      [
       { "params": [ "jobs_pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobs_pending", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Queue time - departments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_ldap_attrib",
     "groupBy": [
      { "params": [ "ldap_attrib" ], "type": "tag" }
     ],
     "measurement": "ldap_attrib_queue_time",
     "select": [
      [
       { "params": [ "queue_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "queue_time", "operator": ">", "value": "0" }
     ]
    }
   ]
  }
 ]
}